### ISSUE TITLE
verify 3.0 schema

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification-schema#4]
This ticket is to verify that the 3.0 schema is complete.  Items from https://github.com/hapi-server/data-specification/blob/master/hapi-3.0.0/changelog.md should be checked below as they are verified.

- [x] Addition of a new endpoint, "about", for server description metadata.
- [x] Ability to specify time-varying bins (#83)
- [x] Ability to use JSON references in info response (#82)
- [x] Ability to indicate a units schema (if one is being used for units strings) (#81)
- [x] Added citation element

**Comment by jbfaden** [comment]
I'm finding it difficult to verify item 3 "Ability to use JSON references in info response (#82)" and I think that's because it's more of a syntax thing than schema.

**Comment by jbfaden** [comment]
This is handled now.  The schema simply allows "$ref" to be one of the properties.
