### ISSUE TITLE
verify 3.1 schema

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification-schema#5]
Version 3.1 brought the new features:
- [x] dataset and parameters may contain unicode
- [x] identify vector coordinate system and components [115](https://github.com/hapi-server/data-specification/issues/115)
- [x] extra metadata with schema [117](https://github.com/hapi-server/data-specification/issues/117)
- [x] maximum time range [136](https://github.com/hapi-server/data-specification/issues/136)

**Comment by jbfaden** [comment]
I've verified that these changes were made in the 3.1 schema.
